### ISSUE TITLE
Is the first argument of setESTDP() presynaptic group or postsynaptic group?

### ISSUE THREAD

**Issue by kilometer3604** [UCI-CARL/CARLsim3#25]
In the example in [User Guide](https://uci-carl.github.io/CARLsim3/ch5_synaptic_plasticity.html#ch5s2_spike_timing_dependent_plasticity), the first argument of `setESTDP` is presynaptic group (`g1`) but described as postsynaptic group.

In the example in [Tutorial](https://uci-carl.github.io/CARLsim3/tut3_plasticity.html), the first argument is postsynaptic group.

So which one is right? Presynaptic or postsynaptic?

And if it's postsynaptic group, how can I implement the following model:
There are three neuron groups A/B/C. Neuron group A connects to B, neuron group C also connects to B. How can I use plasticity on A->B synapses, and fix synapses of C->B?

Thanks a lot!

**Comment by tingshuc** [comment]
Hi Meng, thanks for pointing out the doc error!. We have fixed it. The function setESTDP() should work on post-synaptic group. For your question, just connect(A, B, plastic) and connect(C, B, fixed). Even though you call setESTDP() on B, the connections of C->B are still fixed

**Comment by kilometer3604** [comment]
@tingshuc Thanks for your explanation!
